function [fitresult, gof] = createFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'Fit Curve' fit:
%      X Input: x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-May-2024 16:13:16


%% Fit: 'Fit Curve'.
clc;
Array=csvread('NbSi2 data.csv');
x=Array(:, 1);
y=Array(:, 2);
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'gauss8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.Normalize = 'on';
opts.StartPoint = [5.17320240453253 -0.49238767573532 0.0409096647237643 4.63719043930272 -0.41859022249994 0.0465297141907214 4.60817462628778 -0.567461943688277 0.0487052068226616 3.85060041917511 -0.322957893103168 0.0535461464286036 3.33196340410986 -0.21774894539701 0.0643502701770127 3.12588846076345 -0.648155349891291 0.075810325970372 2.36350340034926 -0.115417280153021 0.0874214991571952 1.75929709492297 0.0645144710719481 0.125744050381741];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Fit Curve' );
h = plot( fitresult, xData, yData);
legend( h, 'NbSi2 Reference', 'Fit Curve', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Energy (eV)', 'Interpreter', 'none' );
ylabel( 'Intensity', 'Interpreter', 'none' );
vline=xline(2370.5, '--b');
vline.HandleVisibility='off';
grid on